In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("Data\8_rent_data.csv")

C:\Users\USER\AppData\Local\Temp\ipykernel_6924\3778509836.py:1: DtypeWarning: Columns (56) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("Data\8_rent_data.csv")

# Khusi Observations

In [3]:
df1=df.copy()

# Swarnava Observations

In [4]:
df2=df.copy()

# Himanshu Observation

### Column info 
1. `Title` column contain rental property info with some highlighted details 
2. `Rental price` column has price of the property which is shown in the website. The unit type are different so need conversion .
3. `Location` column has locality/location details with city name (some has only locality info)
4. `Bed` and `Beds` columns contain Bed number . It should be equal to the "# BHK" in the `Title` column . `Bed` and `Beds` can be merged. Both has *float* data type.
5. `Carpet area` column has the carpet area details in the starting with the mixed unit . From it I have to construct new column `CARPET_AREA` which contains the values in correct unit . And in the last part of the string contains price/sqft of that property.
6. `Baths` and `Bath` column contain the number bathrooms in the rental house . it is in float type.`Bath and Baths` can be merged.
7. `Status` column has two different values . I think this column employs the availability of the property .
15. `Furnishing` column has 7 more non nan value than `Furnished status` . if both column has value then they are same . drop `Furnished status`.
8. `link` column is nothing special can be dropped .
9. `Facing` column has value *south-facing* it can be converted to *south* and same for *east facing*.
10. `Age Of Construction` column has three values `under construction,newly constructed,less than 5 years` . need appropriate binning.  **there has two age of construction column drop first one**. 2nd one has more non nan values . and 2nd one has all the values of the first one also,no data discrepancy .
11. `Overlooking` values can be split in the new column and filled by group by and it can work as a one hot encoding.
12. `Balcony` and `Balconies` column contain the number balconies in the rental house . it is in float type.`Balcony and Balconies` can be merged.
13. `Rental Value` contains the `rental price` and some has monthly/yearly/per sqft maintenance . need to make a new column name `Maintenance Charge`.
14. `Security Deposit` column's unit need to change to make it same scale
16. `Super built area` and `carpet` and `Plot Area` are in complement like if one column has value then other column does not have value .
17. There are two `Floors allowed for construction ` column last one's value will be on earlier column.
18. `Developer` column has the name of construction group/person name 
19. `Project` column has name of the project under which the property was built
20. `Amenities` column has name of special highlighted things that the property is offering . some feature engineering is needed so that some points can be deleted if for that special offer has different column such as lift . or make more column from this column
21. `Price` column has total price of that flat/house.
22. `Configuration` this column has mainly what type of BHK has under the project in which this property is one of them. 
23. I am not able to find any meaning of `Tower & Unit` column data.
24. `Additional Rooms` column has info of different rooms in that property . Can make a new column based on number of rooms/split room type and do missing indicator filling.
25. `Lifts` and `Lift` column contain the number Lifts in the rental house . it is in float type.`Lift and Lifts` can be merged.
26. `Water Availability` column has total hours when the water is available . need feature engineering
27. `Status of Electricity` column has total hour of power cut . can do binning.
28. `Floors allowed for construction` column has maximum number of floors can be built .means in future many floors maximum can be built.
29. `Car parking` and `Covered Parking` columns data are mostly aligned . like if `car parking` has data 3 covered then `covered parking` also has data 3 . but in some cases there has data in `covered parking` but no covered info in `car parking`.
30. `Tower` 
31. `Floors allowed` and `Floor allowed` are in complement if one column has value then other has nan .
32. **Floors allowed and Floors allowed for construction** column mainly contain same info (Hypothesis only ).
33. `Authority Approval` and `Approved` has relation, like `approved` column might be short form of some names of `Authority Approval` column. Need feature engineering. `Authority Approval` column values are name of authority which has given the approval of that property.
34. `Floor` column contains the info of that property that how many floors that flat has and in which floor is available for rent 
35.  `Towers & Units` and `Tower` and `Unit` can be merged or  `Tower & Unit` can be split into `Unit` and `Tower` column . they are disjoint .
36. `Type of Ownership` column has info what kind of ownership that property has
37. `RERA ID` has id of that place where the property is located . Not important 
38. `Any Construction done` column has yes no value . it means small construction is done on that property.
39. `Boundary Wall` column has yes no value means that property has wall or not.
40. `Transaction Type` has two different non null values(rent and resale) . and the data is very less (37 rows has data only)
41. `Additional Features` has very less data. this data has info about construction or has info like "gated colony".
42. `No of Open Sides` has very less data (12) . it has three different values 2 or 3 or 4 
43. Drop `Dimensions(L X B)` column it has info of the `Super built area` column only in length X Breadth
44. `Brokerage Response` has only one value .Drop it.

In [5]:
df3=df.copy()

In [6]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24135 entries, 0 to 24134
Data columns (total 58 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Unnamed: 0                       24135 non-null  int64
 1   Title                            24135 non-null  object
 2   Rental_Price                     24135 non-null  object
 3   Location                         24135 non-null  object
 4   Bed                              3734 non-null   float64
 5   Baths                            19552 non-null  float64
 6   Carpet Area                      15572 non-null  object
 7   Floor                            20497 non-null  object
 8   Status                           23285 non-null  object
 9   Furnished Status                 23831 non-null  object
 10  Rental Value                     23642 non-null  object
 11  Security Deposit                 16735 non-null  object
 12  Address                          24135 non-null  object
 13  Furnishing                       23838 non-null  object
 14  link                             24135 non-null  object
 15  Facing                           16371 non-null  object
 16  Age Of Construction              13324 non-null  object
 17  Flooring                         11888 non-null  object
 18  Overlooking                      15357 non-null  object
 19  Age of Construction              19015 non-null  object
 20  Bath                             4294 non-null   float64
 21  Super Built-up Area              8289 non-null   object
 22  Developer                        9994 non-null   object
 23  Project                          11666 non-null  object
 24  Amenities                        9707 non-null   object
 25  Price                            12340 non-null  object
 26  Price per sqft                   5391 non-null   object
 27  Configuration                    9443 non-null   object
 28  Tower & Unit                     9248 non-null   object
 29  Beds                             20001 non-null  float64
 30  Balcony                          8928 non-null   float64
 31  Balconies                        8286 non-null   float64
 32  Landmarks                        13359 non-null  object
 33  Additional Rooms                 13397 non-null  object
 34  Lifts                            6341 non-null   float64
 35  Water Availability               10374 non-null  object
 36  Status of Electricity            10295 non-null  object
 37  Floors allowed for construction  7152 non-null   float64
 38  Lift                             8218 non-null   float64
 39  Car parking                      7254 non-null   object
 40  Covered Parking                  8313 non-null   float64
 41  Tower                            195 non-null    object
 42  Authority Approval               856 non-null    object
 43  Unit                             945 non-null    object
 44  Type of Ownership                1673 non-null   object
 45  RERA ID                          279 non-null    object
 46  Floors allowed                   14 non-null     float64
 47  Plot Area                        49 non-null     object
 48  Any Construction done            32 non-null     object
 49  Boundary Wall                    32 non-null     object
 50  Transaction Type                 35 non-null     object
 51  Additional Features              16 non-null     object
 52  Approved                         15 non-null     object
 53  Floor allowed                    2 non-null      float64
 54  No of Open Sides                 12 non-null     float64
 55  Dimensions(L X B)                6 non-null      object
 56  Brokerage Response               1 non-null      object
 57  Floors Allowed For Construction  1 non-null      float64
dtypes: float64(14), int64(1), object(43)
memory usage: 10.7+ MB

In [64]:
df3['No of Open Sides'].count()

np.int64(12)

In [41]:
df3['Tower & Unit'].notna().sum()

np.int64(9248)

In [42]:
df3['Tower'].notna().sum()

np.int64(195)

In [43]:
df3['Unit'].notna().sum()

np.int64(945)

In [47]:
df3[df3['Unit'].isna()]['Tower & Unit'].notna().sum()

np.int64(9248)

In [ ]:
#df3.sample(10).transpose()

,1063,13245,2777,599,13020,17196,13223,559,11197,12742
Unnamed: 0,1063,13245,2777,599,13020,17196,13223,559,11197,12742
Title,3 BHK 1550 Sq-ft Flat/Apartment For Rent in L...,3 BHK 1260 Sq-ft Flat/Apartment For Rent in,2 BHK 1000 Sq-ft Flat/Apartment For Rent in,4 BHK 5500 Sq-ft Flat/Apartment For Rent in S...,"3 BHK Flat 1785 Sq-ft For Rent in Honer Aquantis,","2 BHK Flat 1072 Sq-ft For Rent in Brooksdale,",2 BHK 1400 Sq-ft For Rent in,2 BHK 900 Sq-ft Flat/Apartment For Rent in Sh...,3 BHK Builder Floor 100 Sq-yrd For Rent in,3 BHK 1650 Sq-ft For Rent in
Rental_Price,₹1.4 Lac,"₹13,000","₹45,000",₹7.5 Lac,"₹60,000","₹25,000","₹30,000","₹55,000","₹24,000","₹25,000"
Location,"Powai, Mumbai","Sainikpuri, Hyderabad","Satya Nagar Borivali West, Mumbai","Bandra Kurla Complex, Mumbai","Gopanapalli, Hyderabad","Shankar Nagar Pammal, Chennai","Durgabai Deshmukh Colony ( D D Colony), Hyderabad","Powai, Mumbai","Chhattarpur, New Delhi","Kavya evenue, Hyderabad"
Bed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Baths,3.0,3.0,2.0,6.0,3.0,2.0,2.0,2.0,2.0,3.0
Carpet Area,1150sqftsqftsqyrdsqmacrebighahectaremarlakanal...,1260sqftsqftsqyrdsqmacrebighahectaremarlakanal...,NaN,3800sqftsqftsqyrdsqmacrebighahectaremarlakanal...,NaN,900sqftsqftsqyrdsqmacrebighahectaremarlakanalb...,NaN,625sqftsqftsqyrdsqmacrebighahectaremarlakanalb...,NaN,1625sqftsqftsqyrdsqmacrebighahectaremarlakanal...
Floor,16(Out of 24 Floors),1(Out of 4 Floors),5(Out of 7 Floors),6(Out of 22 Floors),6(Out of 30 Floors),11(Out of 11 Floors),NaN,15(Out of 18 Floors),1(Out of 4 Floors),NaN
Status,Immediately,Immediately,Immediately,Immediately,Immediately,Immediately,Immediately,Immediately,Immediately,Immediately
Furnished Status,Semi-Furnished,Semi-Furnished,Unfurnished,Semi-Furnished,Unfurnished,Furnished,Unfurnished,Unfurnished,Semi-Furnished,Semi-Furnished
Rental Value,"₹1.4 Lac|₹10,000Monthly Maintenance","₹13,000|₹1,500Monthly Maintenance","₹45,000",₹7.5 Lac,"₹60,000","₹25,000|₹3,500Monthly Maintenance","₹30,000","₹55,000|₹100Monthly Maintenance","₹24,000","₹25,000|₹1,000Monthly Maintenance"
Security Deposit,₹5.0 Lac,"₹26, 000",NaN,₹30.0 Lac,₹1.3 Lac,₹1.3 Lac,NaN,₹1.5 Lac,NaN,"₹50, 000"
Address,"Powai, Ground Floor, A. M. Naik Tower, Gate No...","201 Raghuram Residency, Sainikpuri, Hyderabad ...","Satya Nagar Borivali West, Mumbai - Western Mu...","Bandra Kurla Complex, Mumbai - Western Mumbai,...","gopanapalli, Gopanapalli, Hyderabad - West, An...","1112 Brooksdale Shankar Nagar Pammal, Shankar ...",B34 Durgabai Deshmukh colony DDColony Bagh Am...,"Near S.M.Shetty School, Chandivali Road, Powai...","B- Block, Chhattarpur, New Delhi - South, Delh...","Moksha Naksh nivas, Road 4B SaiAnurag colony..."
Furnishing,Semi-Furnished,Semi-Furnished,Unfurnished,Semi-Furnished,Unfurnished,Furnished,Unfurnished,Unfurnished,Semi-Furnished,Semi-Furnished
link,https://www.magicbricks.com/propertyDetails/3-...,https://www.magicbricks.com/propertyDetails/3-...,https://www.magicbricks.com/propertyDetails/2-...,https://www.magicbricks.com/propertyDetails/4-...,https://www.magicbricks.com/propertyDetails/3-...,https://www.magicbricks.com/propertyDetails/2-...,https://www.magicbricks.com/propertyDetails/2-...,https://www.magicbricks.com/propertyDetails/2-...,https://www.magicbricks.com/propertyDetails/3-...,https://www.magicbricks.com/propertyDetails/3-...
Facing,East,NaN,NaN,North,East,East,North,East,NaN,NaN
Age Of Construction,NaN,5 to 10 years,NaN,NaN,New Construction,NaN,New Construction,NaN,NaN,New Construction
Flooring,Vitrified,NaN,NaN,NaN,NaN,Vitrified,Mosaic,Vitrified,NaN,NaN
Overlooking,"Garden/Park, Pool, Main Road",NaN,NaN,"Pool, Garden/Park, Main Road","Garden/Park, Pool, Main Road",Main Road,NaN,Garden/Park,NaN,NaN
Age of Construction,NaN,5 to 10 years,NaN,Less than 5 years,New Construction,Less than 5 years,New Construction,15 to 20 years,NaN,New Construction
Bath,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Super Built-up Area,NaN,NaN,1000sqftsqftsqyrdsqmacrebighahectaremarlakanal...,NaN,1785sqftsqftsqyrdsqmacrebighahectaremarlakanal...,NaN,1400sqftsqftsqyrdsqmacrebighahectaremarlakanal...,NaN,100sqyrdsqftsqyrdsqmacrebighahectaremarlakanal...,NaN
Developer,L & T Realty,NaN,NaN,Sunteck Realty Ltd.,Honer Homes,Appaswamy Real Estates Ltd.,NaN,Cooperative Group Housing Society,NaN,NaN
Project,L&T Elixir Reserve,NaN,NaN,Sunteck Signia Isles,Honer Aquantis,Brooksdale,NaN,Shiv Srishti CHS,NaN,NaN
Amenities,"Provision for power backup,Aesthetically desig...",NaN,NaN,"Fire Fighting Equipment,Earth quake resistant,...","Cricket net practice,Half basketball court,Cyc...","Fire Fighting Equipment,Rentable Community Spa...",NaN,NaN,NaN,NaN
Price,₹ 2.80 Cr - ₹ 4.80 Cr,NaN,NaN,₹ 24.0 Cr - ₹ 27.50 Cr,₹ 1.40 Cr - ₹ 2.09 Cr,₹ 60.8 Lac - ₹ 69.8 Lac,NaN,₹ 1.66 Cr - ₹ 2.53 Cr,NaN,NaN
Price per sqft,"₹ 17,650 - ₹ 4.6 Lac",NaN,NaN,"₹ 45,101 - ₹ 69,686","₹ 9,006 - ₹ 11,204",NaN,NaN,NaN,NaN,NaN
Configuration,"2, 3, 4 BHK Flats",NaN,NaN,"4, 5 BHK Flats","2, 3 BHK Flats",NaN,NaN,"2, 3 BHK Flat",NaN,NaN
Tower & Unit,"6 Towers , 300 Units",NaN,NaN,"1 Tower , 80 Units","6 Towers , 1216 Units","2 Towers , 121 Units",NaN,NaN,NaN,NaN
Beds,3.0,3.0,2.0,4.0,3.0,2.0,2.0,2.0,3.0,3.0
Balcony,1.0,NaN,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN
Balconies,NaN,2.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,2.0
Landmarks,"Elixir Reserve, Powai, Mumbai.",NaN,NaN,Bandra Kurla complex,Honor Vivanta,NaN,"B34 is at end of B lane, DD.colony Bagh Ambarp...","Near S.M.Shetty Schoool, Powai",NaN,NaN
Additional Rooms,None of these,NaN,NaN,"Puja Room, Store, Study, Servant Room","Puja Room, Study, Store",NaN,NaN,None of these,NaN,NaN
Lifts,3.0,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN
Water Availability,24 Hours Available,NaN,NaN,NaN,NaN,24 Hours Available,NaN,24 Hours Available,NaN,NaN
Status of Electricity,No/Rare Powercut,NaN,NaN,NaN,NaN,No/Rare Powercut,NaN,No/Rare Powercut,NaN,NaN
Floors allowed for construction,1.0,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN
Lift,3.0,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN
Car parking,1 Covered,NaN,NaN,NaN,NaN,1 Open,NaN,1 Open,NaN,NaN
Covered Parking,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Authority Approval,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type of Ownership,NaN,NaN,NaN,Freehold,NaN,NaN,NaN,NaN,NaN,NaN
RERA ID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Floors allowed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Any Construction done,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Boundary Wall,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Transaction Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Additional Features,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Floor allowed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
No of Open Sides,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dimensions(L X B),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brokerage Response,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Floors Allowed For Construction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
df3['Brokerage Response'].count()

np.int64(1)

In [10]:
df3['Approved'].unique()

array([nan, 'KMDA', 'BDA', 'BMRDA', 'DTCP', 'BBMP', 'HMDA', 'AUDA'],
      dtype=object)

In [12]:
df3[~df3.iloc[0:,16].notna()].iloc[0:,19].notna().sum()

np.int64(5691)

In [13]:
df3[df3.iloc[0:,16].notna()!=df3.iloc[0:,19].notna()].shape

(5691, 58)

In [14]:
df3['Lifts'].notna().sum()

np.int64(6341)

In [15]:
df3['Lift'].notna().sum()

np.int64(8218)

In [16]:
df3[df3['Lifts'].isna()]['Lift'].notna().sum()

np.int64(1877)

In [17]:
df3[df3.iloc[0:,30]==df3.iloc[0:,31]][['Balcony','Balconies']]

Empty DataFrame
Columns: [Balcony, Balconies]
Index: []

In [18]:
df3['Furnishing'].notna().sum()

np.int64(23838)

In [19]:
df3['Furnished Status'].notna().sum()

np.int64(23831)

In [20]:
df3[df3['Furnished Status'].isna()]['Furnishing'].notna().sum()

np.int64(7)

In [22]:
df3['Super Built-up Area'].notna().sum()

np.int64(8289)

In [23]:
df3['Floors allowed for construction'].notna().sum()

np.int64(7152)

In [24]:
df3['Floors Allowed For Construction'].notna().sum()

np.int64(1)

In [25]:
df3['Floors allowed'].notna().sum()

np.int64(14)

In [26]:
df3['Floor allowed'].notna().sum()

np.int64(2)

In [27]:
df3[df3['Floors allowed'].isna()]['Floors allowed for construction'].notna().sum()

np.int64(7138)

In [28]:
df3[df3['Floor allowed'].isna()]['Floors allowed for construction'].notna().sum()

np.int64(7150)

In [29]:
df3['Floors allowed'].unique()

array([nan,  3.,  9.,  6.,  4.,  5.,  2.])